---

- name: Write my.cnf
  ansible.builtin.template:
    dest: "/var/lib/prometheus/.my.cnf"
    src: "my.cnf.j2"

- name: Install python3-mysql -pip
  ansible.builtin.apt:
    name: "python3-mysqldb"
    state: present

#- name: Install python-mysql pip
#  ansible.builtin.pip:
#    name: "python3-mysql"
#    state: present

- name: Create mysqld exporter user
  community.mysql.mysql_user:
    name: "{{ mysqld_exporter_user }}"
    password: "{{ mysqld_exporter_password }}"
    priv: "*.*:PROCESS, REPLICATION CLIENT, SELECT"
    check_implicit_admin: yes
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - prometheus-mysqld-exporter







